{% set name = "lda" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76fc6fbb066b6d1ec0360a1541c5e1c8b69a728666525e72644c4d5332fc778a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson-python                  # [build_platform != target_platform]
    - python                        # [build_platform != target_platform]
  host:
    - cython
    - meson-python
    - pip
    - poetry-core
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - pip check
  imports:
    - lda
    - lda.datasets
    - lda.utils
  requires:
    - pip
    - python

about:
  home: https://lda.readthedocs.io/en/latest/
  license: MPL-2.0
  license_file: LICENSE
  summary: lda implements latent Dirichlet allocation (LDA) using collapsed Gibbs sampling. lda is fast and is tested on Linux, OS X, and Windows.
  doc_url: https://lda.readthedocs.io/en/latest/
  dev_url: https://github.com/ariddell/lda/tree/master

extra:
  recipe-maintainers:
    - danielnachun
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
